import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, LockKeyhole, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';

export default async function DemoPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  let payload: { url: string; result: any; exp: number } | null = null;
  try { payload = JSON.parse(Buffer.from(id, 'base64url').toString()); } catch { notFound(); }
  if (!payload || payload.exp < Date.now()) notFound();
  const r = payload.result;
  const scores=[['Performance',r.performance],['SEO',r.seo],['Accessibility',r.accessibility],['Best Practices',r.bestPractices]];
  return <main className="min-h-screen bg-[#070707] px-4 py-6 text-white sm:px-8"><div className="mx-auto max-w-5xl"><Link href="/" className="inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-white"><ArrowLeft className="h-4 w-4"/>Back</Link><div className="mt-10 rounded-3xl border border-white/[.08] bg-[#0d0d0d] p-6 sm:p-10"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[.26em] text-rose">Demo audit</p><h1 className="mt-3 break-all text-2xl font-medium sm:text-4xl">{payload.url}</h1></div><div className="grid h-28 w-28 place-items-center rounded-full border-[7px] border-magenta/70"><div className="text-center"><div className="text-3xl font-semibold">{r.overall}</div><div className="text-[10px] text-zinc-500">OVERALL</div></div></div></div><div className="mt-10 grid gap-3 sm:grid-cols-4">{scores.map(([label,score])=><div key={label as string} className="rounded-2xl border border-white/[.07] bg-black/30 p-4"><div className="text-2xl font-medium">{score as number}</div><div className="mt-1 text-xs text-zinc-500">{label as string}</div></div>)}</div><div className="mt-10 overflow-hidden rounded-2xl border border-white/[.08]"><div className="border-b border-white/[.08] p-5"><h2 className="text-lg">Top issues</h2></div>{r.issues.map((issue:any)=><div key={issue.key} className="border-b border-white/[.06] p-5 last:border-0"><div className="flex items-start justify-between gap-4"><div><h3>{issue.title}</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">{issue.explanation}</p></div><span className="rounded-full border border-magenta/30 bg-magenta/10 px-2.5 py-1 text-[10px] text-rose">{issue.severity}</span></div></div>)}</div><div className="mt-8 rounded-2xl border border-white/[.08] bg-gradient-to-r from-magenta/10 to-transparent p-6"><div className="flex items-start gap-3"><LockKeyhole className="mt-1 h-5 w-5 text-rose"/><div><h3 className="text-lg">Full report + PDF is locked</h3><p className="mt-2 text-sm text-zinc-500">Create your free account to save audits, add agency branding, generate PDF, and share a client link.</p><Button asChild variant="accent" className="mt-5"><Link href="/signup"><Zap className="h-4 w-4"/>Unlock free reports</Link></Button></div></div></div></div></div></main>;
}
