import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AlertTriangle, ArrowLeft, Save, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { DownloadDemoPdfButton } from '@/components/report/download-demo-pdf-button';
import { decodeGuestPayload } from '@/lib/audit/guest-payload';

type GuestPayload = { url: string; result: any; language?: string; exp: number };

export default async function DemoPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams?: Promise<{ mode?: string }> }) {
  const { id } = await params;
  const mode = (await searchParams)?.mode === 'developer' ? 'developer' : 'business';
  let payload: GuestPayload | null = null;
  try { payload = decodeGuestPayload<GuestPayload>(id); } catch { notFound(); }
  if (!payload || payload.exp < Date.now()) notFound();
  const r = payload.result;
  const scores = [['Performance', r.performance], ['SEO', r.seo], ['Accessibility', r.accessibility], ['Best Practices', r.bestPractices]];
  const business = r.businessReport;
  const developer = r.developerReport;
  const findings = mode === 'business' ? (business?.findings || r.issues || []) : (developer?.findings || r.findings || r.issues || []);

  return <main className="min-h-screen bg-[#070707] px-4 py-6 text-white sm:px-8"><div className="mx-auto max-w-6xl"><Link href="/" className="inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-white"><ArrowLeft className="h-4 w-4" />Back</Link><div className="mt-8 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs uppercase tracking-[.26em] text-rose">{mode === 'business' ? 'Business Owner Report' : 'Developer Report'}</p><h1 className="mt-3 break-all text-2xl font-medium sm:text-4xl">{payload.url}</h1><p className="mt-3 text-xs text-zinc-600">{r.source || 'Scoryn normalized audit'}</p></div><div className="flex flex-wrap gap-2"><DownloadDemoPdfButton reportId={id} mode="business" /><DownloadDemoPdfButton reportId={id} mode="developer" /></div></div>{r.partial && <div className="mt-6 flex gap-3 rounded-2xl border border-amber-400/10 bg-amber-400/[.035] p-4"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-300" /><p className="text-sm leading-6 text-zinc-500">Some external checks were unavailable. Scoryn is showing verified evidence and leaving unavailable metrics blank.</p></div>}<div className="mt-6 grid gap-3 sm:grid-cols-4">{scores.map(([label, score]) => <div key={String(label)} className="rounded-2xl border border-white/[.07] bg-[#0d0d0d] p-4"><div className="text-2xl font-medium">{typeof score === 'number' ? score : '—'}</div><div className="mt-1 text-xs text-zinc-500">{String(label)}</div></div>)}</div><div className="mt-6 flex flex-wrap gap-2 rounded-2xl border border-white/[.07] bg-[#0d0d0d] p-2"><Link href={`/demo/${id}?mode=business`} className={`rounded-xl px-4 py-2 text-sm ${mode === 'business' ? 'bg-magenta/[.12] text-rose' : 'text-zinc-500'}`}>Business Owner Report</Link><Link href={`/demo/${id}?mode=developer`} className={`rounded-xl px-4 py-2 text-sm ${mode === 'developer' ? 'bg-magenta/[.12] text-rose' : 'text-zinc-500'}`}>Developer Report</Link></div>{mode === 'business' ? <Business report={business} findings={findings} /> : <Developer report={developer} findings={findings} />}<div className="mt-8 rounded-2xl border border-white/[.08] bg-gradient-to-r from-magenta/10 to-transparent p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-lg">Save this audit to history</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">Login ke baad future audits, both report modes, branded PDFs aur share links workspace history mein save honge.</p></div><Button asChild variant="accent"><Link href="/signup"><Save className="h-4 w-4" /><Zap className="h-4 w-4" />Create free account</Link></Button></div></div></div></main>;
}

function Business({ report, findings }: { report: any; findings: any[] }) { return <section className="mt-6 space-y-5"><div className="rounded-3xl border border-white/[.08] bg-[#0d0d0d] p-6"><p className="text-xs uppercase tracking-[.24em] text-rose">SCORYN WEBSITE HEALTH REPORT</p><p className="mt-4 max-w-3xl text-sm leading-7 text-zinc-400">{report?.summary || 'Scoryn completed the available website checks.'}</p><div className="mt-6 grid gap-5 md:grid-cols-2"><List title="What’s working well" items={report?.workingWell} /><List title="What needs attention" items={report?.needsAttention} /><List title="What your customers may experience" items={report?.customerExperience} /><div><h3 className="text-sm text-zinc-300">What may affect Google visibility</h3><p className="mt-2 text-sm leading-6 text-zinc-500">{report?.googleVisibility || 'Technical SEO checks do not confirm actual Google search ranking.'}</p></div></div></div><div className="space-y-3"><h2 className="text-2xl">Top priorities</h2>{findings.length ? findings.slice(0, 12).map((finding, index) => <details key={finding.findingId || finding.key || index} className="rounded-2xl border border-white/[.08] bg-[#0d0d0d] p-5"><summary className="cursor-pointer list-none"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-wider text-zinc-700">{finding.where || finding.affectedUrl || 'Affected page'}</p><h3 className="mt-2">{finding.problem || finding.title}</h3><p className="mt-2 text-sm leading-6 text-zinc-500">{finding.customerExperience || finding.explanation}</p></div><span className="rounded-full border border-magenta/30 bg-magenta/10 px-2.5 py-1 text-[10px] text-rose">{finding.importance || finding.severity}</span></div></summary><div className="mt-4 border-t border-white/[.06] pt-4 text-sm leading-6 text-zinc-500"><p><span className="text-zinc-700">Business impact: </span>{finding.businessImpact}</p><p className="mt-2"><span className="text-zinc-700">Recommended action: </span>{finding.recommendedAction || finding.developerFix}</p>{finding.technicalEvidence && <p className="mt-2 text-xs text-zinc-700">Technical details: {finding.technicalEvidence}</p>}</div></details>) : <div className="rounded-2xl border border-white/[.07] p-6 text-sm text-zinc-600">No priority issues were found.</div>}</div></section>; }

function Developer({ report, findings }: { report: any; findings: any[] }) { return <section className="mt-6 space-y-5"><div className="rounded-3xl border border-white/[.08] bg-[#0d0d0d] p-6"><p className="text-xs uppercase tracking-[.24em] text-rose">SCORYN DEVELOPER AUDIT REPORT</p><p className="mt-4 text-sm leading-7 text-zinc-400">{report?.summary || 'Detailed evidence from the completed audit.'}</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(report?.engineStatus || {}).filter(([key]) => key !== 'errors').map(([key, value]) => <div key={key} className="rounded-xl border border-white/[.06] bg-black/20 p-3"><div className="text-[10px] uppercase tracking-wider text-zinc-700">{key}</div><div className="mt-2 text-xs text-zinc-300">{String(value)}</div></div>)}</div></div><div className="space-y-3"><h2 className="text-2xl">Actionable findings</h2>{findings.length ? findings.slice(0, 24).map((finding, index) => <details key={finding.id || finding.findingId || index} className="rounded-2xl border border-white/[.08] bg-[#0d0d0d] p-5"><summary className="cursor-pointer list-none"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-wider text-zinc-700">{finding.category} · {finding.source}</p><h3 className="mt-2">{finding.title}</h3><p className="mt-2 text-sm leading-6 text-zinc-500">{finding.evidence || finding.description || finding.explanation}</p></div><span className="rounded-full border border-magenta/30 bg-magenta/10 px-2.5 py-1 text-[10px] text-rose">{finding.severity}</span></div></summary><div className="mt-4 grid gap-3 border-t border-white/[.06] pt-4 text-sm leading-6 md:grid-cols-2"><Detail label="Affected URL" value={finding.affectedUrl} /><Detail label="Measured / recommended" value={`${finding.measuredValue ?? 'Not reported'} / ${finding.recommendedValue ?? 'Not reported'}`} /><Detail label="Element / selector / resource" value={[finding.affectedElement, finding.selector, finding.resourceUrl].filter(Boolean).join(' · ') || 'Not reported'} /><Detail label="Exact fix" value={finding.developerFix || 'No scanner-specific fix returned.'} /></div></details>) : <div className="rounded-2xl border border-white/[.07] p-6 text-sm text-zinc-600">No actionable issues were found.</div>}</div><p className="rounded-2xl border border-white/[.07] p-5 text-sm text-zinc-600">{report?.ranking?.note || 'Technical SEO checks do not confirm actual Google search ranking.'}</p></section>; }
function List({ title, items }: { title: string; items?: unknown }) { const values = Array.isArray(items) ? items.filter((item): item is string => typeof item === 'string') : []; return <div><h3 className="text-sm text-zinc-300">{title}</h3><ul className="mt-2 space-y-2 text-sm leading-6 text-zinc-500">{(values.length ? values : ['No additional note from the completed checks.']).slice(0, 6).map((item, index) => <li key={index}>• {item}</li>)}</ul></div>; }
function Detail({ label, value }: { label: string; value: unknown }) { return <div><div className="text-[10px] uppercase tracking-wider text-zinc-700">{label}</div><div className="mt-1 break-words text-zinc-400">{value === null || value === undefined || value === '' ? 'Not reported' : String(value)}</div></div>; }
