import { initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { onDocumentCreated } from 'firebase-functions/v2/firestore';
import { defineSecret, defineString } from 'firebase-functions/params';

initializeApp();
const db=getFirestore();
const pageSpeedKey=defineSecret('PAGESPEED_API_KEY');
const nvidiaKey=defineSecret('NVIDIA_API_KEY');
const nvidiaModel=defineString('NVIDIA_MODEL',{default:'meta/llama-3.1-70b-instruct'});
const nvidiaBase=defineString('NVIDIA_BASE_URL',{default:'https://integrate.api.nvidia.com/v1'});
const demoMode=defineString('DEMO_AUDIT_MODE',{default:'false'});

type Scores={performance:number;seo:number;accessibility:number;bestPractices:number};
type Issue={key:string;title:string;category:string;severity:string;technicalDetail:string;explanation:string;businessImpact:string};

function fallback(issue:any){const title=issue?.title||'Website improvement detected';const lower=title.toLowerCase();if(lower.includes('image'))return {explanation:'Some images are heavier than necessary and can slow down the page, especially on mobile.',businessImpact:'Faster image delivery improves first impressions and reduces friction before a visitor reaches your offer.'};if(lower.includes('contentful')||lower.includes('paint'))return {explanation:'Important page content takes longer than ideal to become visible to visitors.',businessImpact:'A slower first view can reduce engagement and make potential customers leave before they understand the offer.'};if(lower.includes('meta')||lower.includes('seo'))return {explanation:'Search engines may not be getting the clearest possible description of this page.',businessImpact:'Clearer search information can help the right prospects understand the business before they click.'};return {explanation:'This technical issue affects the quality or reliability of the website experience.',businessImpact:'Fixing it can make the site easier to use and reduce unnecessary friction for potential customers.'}}

async function runPSI(url:string,strategy:'mobile'|'desktop',key:string){const endpoint=new URL('https://www.googleapis.com/pagespeedonline/v5/runPagespeed');endpoint.searchParams.set('url',url);endpoint.searchParams.set('strategy',strategy);for(const c of ['performance','seo','accessibility','best-practices'])endpoint.searchParams.append('category',c);if(key)endpoint.searchParams.set('key',key);const r=await fetch(endpoint);if(!r.ok)throw new Error(`PageSpeed ${strategy} failed: ${r.status}`);return r.json() as Promise<any>}
function scores(x:any):Scores{const c=x.lighthouseResult?.categories||{};return {performance:Math.round((c.performance?.score||0)*100),seo:Math.round((c.seo?.score||0)*100),accessibility:Math.round((c.accessibility?.score||0)*100),bestPractices:Math.round((c['best-practices']?.score||0)*100)}}
function merge(a:Scores,b:Scores):Scores{return {performance:Math.round((a.performance+b.performance)/2),seo:Math.round((a.seo+b.seo)/2),accessibility:Math.round((a.accessibility+b.accessibility)/2),bestPractices:Math.round((a.bestPractices+b.bestPractices)/2)}}
function severity(score:number){return score<.5?'HIGH':score<.8?'MEDIUM':'LOW'}
function extractIssues(x:any){const audits=x.lighthouseResult?.audits||{};return Object.entries(audits).filter(([,v]:any)=>typeof v?.score==='number'&&v.score<.9&&v.scoreDisplayMode!=='notApplicable').sort(([,a]:any,[,b]:any)=>(a.score||0)-(b.score||0)).slice(0,12).map(([key,v]:any)=>({key,title:v.title||key,technicalDetail:v.description||'',severity:severity(v.score),category:key.includes('seo')?'SEO':'PERFORMANCE'}))}
async function explain(issue:any,language:string,key:string){if(!key)return fallback(issue);try{const r=await fetch(`${nvidiaBase.value()}/chat/completions`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${key}`},body:JSON.stringify({model:nvidiaModel.value(),temperature:.2,max_tokens:180,messages:[{role:'system',content:'You are a web consultant. Never invent percentages, revenue loss, customer loss, or unsupported statistics. Return valid JSON only.'},{role:'user',content:`Explain this website audit issue for a non-technical business owner in ${language}. Max 2 short sentences per field. Return JSON with keys explanation and businessImpact. Issue: ${JSON.stringify({title:issue.title,detail:issue.technicalDetail})}`}]})});if(!r.ok)throw new Error('AI failed');const j:any=await r.json();const text=j.choices?.[0]?.message?.content||'';const cleaned=text.replace(/^```json\s*|```$/g,'').trim();const out=JSON.parse(cleaned);if(!out.explanation||!out.businessImpact)throw new Error('Bad AI shape');return {explanation:String(out.explanation),businessImpact:String(out.businessImpact)}}catch{return fallback(issue)}}
function demo(url:string){let h=0;for(const c of url)h=(h*31+c.charCodeAt(0))>>>0;const n=(o:number,m:number,s:number)=>m+((h>>o)%s);return {performance:n(0,55,39),seo:n(4,72,25),accessibility:n(8,68,29),bestPractices:n(12,70,27)}}

function buildDualReports(url:string,merged:Scores,rawIssues:any[],language:string){const businessFindings=rawIssues.map((issue:any,index:number)=>({findingId:`${issue.key}-${index}`,problem:issue.title,where:url.includes('/')?new URL(url).pathname==='/'?'Homepage':new URL(url).pathname:url,customerExperience:issue.explanation||issue.technicalDetail,businessImpact:issue.businessImpact,importance:issue.severity,recommendedAction:issue.technicalDetail||'Review the Lighthouse evidence and apply the smallest safe fix.',technicalEvidence:issue.measuredValue||issue.technicalDetail||null}));return {business:{mode:'business-owner',language,title:'SCORYN WEBSITE HEALTH REPORT',summary:businessFindings.length?'The website is working, but a few verified technical issues may affect the visitor experience.':'The available checks did not find a priority issue on this website.',workingWell:[merged.performance>=90?'Main speed checks are in a healthy range.':'The audit completed with verified website evidence.'],needsAttention:businessFindings.slice(0,5).map((item:any)=>`${item.problem} — ${item.where}`),customerExperience:businessFindings.slice(0,4).map((item:any)=>item.customerExperience),googleVisibility:rawIssues.some((item:any)=>item.category==='SEO')?'Technical SEO checks found items that may make it harder for search engines to understand this page.':'Technical SEO checks passed for the signals that were available. This audit does not confirm actual Google ranking.',rankingDisclaimer:'Actual Google search ranking cannot be confirmed without Search Console or ranking data.',topPriorities:businessFindings.slice(0,3).map((item:any)=>({findingId:item.findingId,title:item.problem,reason:item.businessImpact})),findings:businessFindings,nextSteps:businessFindings.slice(0,3).map((item:any)=>item.recommendedAction)},developer:{mode:'developer',language,title:'SCORYN DEVELOPER AUDIT REPORT',summary:'Detailed evidence from the Firebase background audit worker.',scores:{...merged,overall:Math.round((merged.performance+merged.seo+merged.accessibility+merged.bestPractices)/4)},pages:[{url,finalUrl:url}],metrics:{},infrastructure:{},engineStatus:{pageSpeed:'complete',htmlChecks:'partial',unlighthouse:'fallback-discovery',axeCore:'lighthouse-fallback',webCheck:'unavailable',errors:[]},findings:rawIssues.map((issue:any,index:number)=>({...issue,id:`${issue.key}-${index}`,source:'PAGESPEED_LIGHTHOUSE',affectedUrl:url,metric:issue.metric||null,measuredValue:issue.measuredValue||null,recommendedValue:issue.recommendedValue||null,affectedElement:issue.affectedElement||null,selector:issue.selector||null,resourceUrl:issue.resourceUrl||null,confidence:'HIGH',evidence:issue.technicalDetail||issue.title,likelyCause:null,developerFix:issue.technicalDetail||null})),ranking:{searchConsoleConnected:false,actualGoogleRankingAvailable:false,note:'Technical SEO checks do not confirm actual Google search ranking.'}}}}

export const processAudit=onDocumentCreated({document:'auditJobs/{jobId}',secrets:[pageSpeedKey,nvidiaKey],timeoutSeconds:300,memory:'1GiB'},async(event)=>{const job=event.data?.data();if(!job||job.workerMode==='github-actions')return;const auditId=job.auditId as string;const auditRef=db.collection('audits').doc(auditId);try{await auditRef.update({status:'RUNNING',currentStep:'DISCOVERING_PAGES',progress:8,updatedAt:new Date()});let merged:Scores,rawIssues:any[]=[];if(demoMode.value()==='true'){merged=demo(job.url);rawIssues=[{key:'largest-contentful-paint',title:'Largest Contentful Paint can be improved',technicalDetail:'The largest visible content element is rendered later than ideal.',severity:'HIGH',category:'PERFORMANCE'},{key:'image-optimization',title:'Images are heavier than necessary',technicalDetail:'Several images can use modern formats or stronger compression.',severity:'MEDIUM',category:'PERFORMANCE'},{key:'meta-description',title:'Search snippet can be clearer',technicalDetail:'Metadata can more clearly describe the page offering.',severity:'MEDIUM',category:'SEO'}]}else{await auditRef.update({currentStep:'TESTING_SPEED',progress:20,updatedAt:new Date()});const key=pageSpeedKey.value();const [mobile,desktop]=await Promise.all([runPSI(job.url,'mobile',key),runPSI(job.url,'desktop',key)]);await auditRef.update({currentStep:'CHECKING_SEO',progress:48,updatedAt:new Date()});merged=merge(scores(mobile),scores(desktop));rawIssues=[...extractIssues(mobile),...extractIssues(desktop)].filter((x,i,a)=>a.findIndex(y=>y.key===x.key)===i).slice(0,16);await db.collection('auditRuns').doc(`${auditId}_mobile`).set({auditId,device:'MOBILE',scores:scores(mobile),rawLighthouse:mobile.lighthouseResult||null,createdAt:new Date()});await db.collection('auditRuns').doc(`${auditId}_desktop`).set({auditId,device:'DESKTOP',scores:scores(desktop),rawLighthouse:desktop.lighthouseResult||null,createdAt:new Date()})}
await auditRef.update({currentStep:'AI_ANALYSIS',progress:68,updatedAt:new Date()});const brand=await db.collection('branding').doc(job.workspaceId).get();const language=brand.data()?.reportLanguage||'ENGLISH';for(const issue of rawIssues){const ai=await explain(issue,language,nvidiaKey.value());await db.collection('auditIssues').doc(`${auditId}_${issue.key}`).set({auditId,...issue,...ai,createdAt:new Date()})}
await auditRef.update({currentStep:'BUILDING_REPORT',progress:90,updatedAt:new Date()});const overall=Math.round((merged.performance+merged.seo+merged.accessibility+merged.bestPractices)/4);const publicSlug=`${auditId.slice(0,8)}-${Math.random().toString(36).slice(2,8)}`;const reports=buildDualReports(job.url,merged,rawIssues,String(job.language||'ENGLISH'));await auditRef.update({status:'COMPLETED',currentStep:'COMPLETE',progress:100,overallScore:overall,performanceScore:merged.performance,seoScore:merged.seo,accessibilityScore:merged.accessibility,bestPracticesScore:merged.bestPractices,rawAuditData:{requestedUrl:job.url,resolvedUrl:job.url,testedAt:new Date().toISOString(),pages:reports.developer.pages,scores:reports.developer.scores,findings:reports.developer.findings,engines:reports.developer.engineStatus},businessReport:reports.business,developerReport:reports.developer,engineStatus:reports.developer.engineStatus,reportLanguage:job.language||'ENGLISH',publicSlug,isPublic:true,completedAt:new Date(),updatedAt:new Date()});await event.data?.ref.update({status:'COMPLETED',completedAt:new Date()});}catch(e){await auditRef.update({status:'FAILED',currentStep:'FAILED',progress:100,errorMessage:e instanceof Error?e.message:'Audit failed',updatedAt:new Date()});await event.data?.ref.update({status:'FAILED',error:e instanceof Error?e.message:'Audit failed',completedAt:new Date()})}});
