import { NextResponse } from 'next/server';
import { Font, renderToBuffer } from '@react-pdf/renderer';
import { ReportPDF } from '@/lib/report/pdf';

const fontFamilies:Record<string,string>={
  HINDI:'Noto Sans Devanagari',
  MARATHI:'Noto Sans Devanagari',
  BENGALI:'Noto Sans Bengali',
  GUJARATI:'Noto Sans Gujarati',
  TAMIL:'Noto Sans Tamil',
  TELUGU:'Noto Sans Telugu'
};

const registeredFonts=new Set<string>();

async function ensureReportFont(language:string|undefined){
  const googleFamily=language?fontFamilies[language]:undefined;
  if(!googleFamily) return 'Helvetica';

  const pdfFamily='Scoryn '+googleFamily;
  if(registeredFonts.has(pdfFamily)) return pdfFamily;

  try{
    const cssUrl='https://fonts.googleapis.com/css2?family='+encodeURIComponent(googleFamily)+':wght@400&display=swap';
    const cssRes=await fetch(cssUrl,{cache:'force-cache',headers:{'user-agent':'Mozilla/5.0'}});
    if(!cssRes.ok) return 'Helvetica';
    const css=await cssRes.text();
    const match=css.match(/src:\s*url\((https:[^)]+)\)\s*format\(['\"]woff2['\"]\)/i);
    const src=match?.[1];
    if(!src) return 'Helvetica';
    Font.register({family:pdfFamily,src,fontWeight:400});
    registeredFonts.add(pdfFamily);
    return pdfFamily;
  }catch(e){
    console.error('[Scoryn demo PDF font]',e);
    return 'Helvetica';
  }
}

export async function POST(req:Request){
  try{
    const body=await req.json().catch(()=>({}));
    const id=typeof body?.id==='string'?body.id:'';
    if(!id) return NextResponse.json({error:'Missing report data.'},{status:400});

    let payload:any;
    try{
      payload=JSON.parse(Buffer.from(id,'base64url').toString());
    }catch{
      return NextResponse.json({error:'Invalid report data.'},{status:400});
    }

    if(!payload?.url||!payload?.result||typeof payload?.exp!=='number'||payload.exp<Date.now()){
      return NextResponse.json({error:'This demo report has expired. Run the audit again.'},{status:410});
    }

    const r=payload.result;
    const language=typeof payload.language==='string'?payload.language:'ENGLISH';
    const data={
      audit:{
        url:payload.url,
        overallScore:typeof r.overall==='number'?r.overall:null,
        performanceScore:typeof r.performance==='number'?r.performance:null,
        seoScore:typeof r.seo==='number'?r.seo:null,
        accessibilityScore:typeof r.accessibility==='number'?r.accessibility:null,
        bestPracticesScore:typeof r.bestPractices==='number'?r.bestPractices:null,
        partial:Boolean(r.partial),
        reportLanguage:language
      },
      branding:{
        agencyName:'Scoryn',
        signature:'Basic audit PDF generated by Scoryn. Create an account only if you want saved history, custom branding and client management.',
        whatsapp:'',
        email:'',
        phone:''
      },
      issues:Array.isArray(r.issues)?r.issues:[]
    };

    const fontFamily=await ensureReportFont(language);
    const buf=await renderToBuffer(ReportPDF({data,fontFamily}));
    return new NextResponse(buf as any,{
      headers:{
        'Content-Type':'application/pdf',
        'Content-Disposition':'attachment; filename="scoryn-demo-audit.pdf"',
        'Cache-Control':'private, no-store'
      }
    });
  }catch(e){
    console.error('[Scoryn demo PDF]',e);
    return NextResponse.json({error:'PDF generate nahi ho paya. Please retry.'},{status:500});
  }
}
